// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CreateOrLoadPlayerHandler(ReducerEventContext ctx, string requestedName);
        public event CreateOrLoadPlayerHandler? OnCreateOrLoadPlayer;

        public void CreateOrLoadPlayer(string requestedName)
        {
            conn.InternalCallReducer(new Reducer.CreateOrLoadPlayer(requestedName));
        }

        public bool InvokeCreateOrLoadPlayer(ReducerEventContext ctx, Reducer.CreateOrLoadPlayer args)
        {
            if (OnCreateOrLoadPlayer == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCreateOrLoadPlayer(
                ctx,
                args.RequestedName
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CreateOrLoadPlayer : Reducer, IReducerArgs
        {
            [DataMember(Name = "requested_name")]
            public string RequestedName;

            public CreateOrLoadPlayer(string RequestedName)
            {
                this.RequestedName = RequestedName;
            }

            public CreateOrLoadPlayer()
            {
                this.RequestedName = "";
            }

            string IReducerArgs.ReducerName => "create_or_load_player";
        }
    }
}
