// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void PlayerIsReadyHandler(ReducerEventContext ctx, ulong matchId);
        public event PlayerIsReadyHandler? OnPlayerIsReady;

        public void PlayerIsReady(ulong matchId)
        {
            conn.InternalCallReducer(new Reducer.PlayerIsReady(matchId));
        }

        public bool InvokePlayerIsReady(ReducerEventContext ctx, Reducer.PlayerIsReady args)
        {
            if (OnPlayerIsReady == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnPlayerIsReady(
                ctx,
                args.MatchId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class PlayerIsReady : Reducer, IReducerArgs
        {
            [DataMember(Name = "match_id")]
            public ulong MatchId;

            public PlayerIsReady(ulong MatchId)
            {
                this.MatchId = MatchId;
            }

            public PlayerIsReady()
            {
            }

            string IReducerArgs.ReducerName => "player_is_ready";
        }
    }
}
