// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ShootHandler(ReducerEventContext ctx, float timeInMilSeconds, ulong matchId);
        public event ShootHandler? OnShoot;

        public void Shoot(float timeInMilSeconds, ulong matchId)
        {
            conn.InternalCallReducer(new Reducer.Shoot(timeInMilSeconds, matchId));
        }

        public bool InvokeShoot(ReducerEventContext ctx, Reducer.Shoot args)
        {
            if (OnShoot == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnShoot(
                ctx,
                args.TimeInMilSeconds,
                args.MatchId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class Shoot : Reducer, IReducerArgs
        {
            [DataMember(Name = "time_in_mil_seconds")]
            public float TimeInMilSeconds;
            [DataMember(Name = "match_id")]
            public ulong MatchId;

            public Shoot(
                float TimeInMilSeconds,
                ulong MatchId
            )
            {
                this.TimeInMilSeconds = TimeInMilSeconds;
                this.MatchId = MatchId;
            }

            public Shoot()
            {
            }

            string IReducerArgs.ReducerName => "shoot";
        }
    }
}
