// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class MatchHandle : RemoteTableHandle<EventContext, Match>
        {
            public override string RemoteTableName => "match";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Match row) => row.Id;

                public IdUniqueIndex(MatchHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal MatchHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(Match row) => row.Id;
        }

        public readonly MatchHandle Match;
    }

    public sealed class MatchCols
    {
        public global::SpacetimeDB.Col<Match, ulong> Id { get; }
        public global::SpacetimeDB.Col<Match, SpacetimeDB.Identity> LeftPlayer { get; }
        public global::SpacetimeDB.Col<Match, SpacetimeDB.Identity> RightPlayer { get; }
        public global::SpacetimeDB.Col<Match, int> State { get; }
        public global::SpacetimeDB.Col<Match, SpacetimeDB.Identity> Winner { get; }
        public global::SpacetimeDB.Col<Match, float> TimeInMilSecondPlayerLeft { get; }
        public global::SpacetimeDB.Col<Match, float> TimeInMilSecondsPlayerRight { get; }
        public global::SpacetimeDB.Col<Match, bool> LeftPlayerReady { get; }
        public global::SpacetimeDB.Col<Match, bool> RightPlayerReady { get; }

        public MatchCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<Match, ulong>(tableName, "id");
            LeftPlayer = new global::SpacetimeDB.Col<Match, SpacetimeDB.Identity>(tableName, "left_player");
            RightPlayer = new global::SpacetimeDB.Col<Match, SpacetimeDB.Identity>(tableName, "right_player");
            State = new global::SpacetimeDB.Col<Match, int>(tableName, "state");
            Winner = new global::SpacetimeDB.Col<Match, SpacetimeDB.Identity>(tableName, "winner");
            TimeInMilSecondPlayerLeft = new global::SpacetimeDB.Col<Match, float>(tableName, "time_in_mil_second_player_left");
            TimeInMilSecondsPlayerRight = new global::SpacetimeDB.Col<Match, float>(tableName, "time_in_mil_seconds_player_right");
            LeftPlayerReady = new global::SpacetimeDB.Col<Match, bool>(tableName, "left_player_ready");
            RightPlayerReady = new global::SpacetimeDB.Col<Match, bool>(tableName, "right_player_ready");
        }
    }

    public sealed class MatchIxCols
    {
        public global::SpacetimeDB.IxCol<Match, ulong> Id { get; }

        public MatchIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<Match, ulong>(tableName, "id");
        }
    }
}
