// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class WinstreakHandle : RemoteTableHandle<EventContext, WinStreak>
        {
            protected override string RemoteTableName => "winstreak";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(WinStreak row) => row.Id;

                public IdUniqueIndex(WinstreakHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class PlayerIdentityIndex : BTreeIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(WinStreak row) => row.PlayerIdentity;

                public PlayerIdentityIndex(WinstreakHandle table) : base(table) { }
            }

            public readonly PlayerIdentityIndex PlayerIdentity;

            internal WinstreakHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                PlayerIdentity = new(this);
            }

            protected override object GetPrimaryKey(WinStreak row) => row.Id;
        }

        public readonly WinstreakHandle Winstreak;
    }

    public sealed class WinstreakCols
    {
        public global::SpacetimeDB.Col<WinStreak, ulong> Id { get; }
        public global::SpacetimeDB.Col<WinStreak, SpacetimeDB.Identity> PlayerIdentity { get; }
        public global::SpacetimeDB.Col<WinStreak, int> CurrentWinStreak { get; }
        public global::SpacetimeDB.Col<WinStreak, int> MaxWinStreak { get; }

        public WinstreakCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<WinStreak, ulong>(tableName, "id");
            PlayerIdentity = new global::SpacetimeDB.Col<WinStreak, SpacetimeDB.Identity>(tableName, "player_identity");
            CurrentWinStreak = new global::SpacetimeDB.Col<WinStreak, int>(tableName, "current_win_streak");
            MaxWinStreak = new global::SpacetimeDB.Col<WinStreak, int>(tableName, "max_win_streak");
        }
    }

    public sealed class WinstreakIxCols
    {
        public global::SpacetimeDB.IxCol<WinStreak, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<WinStreak, SpacetimeDB.Identity> PlayerIdentity { get; }

        public WinstreakIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<WinStreak, ulong>(tableName, "id");
            PlayerIdentity = new global::SpacetimeDB.IxCol<WinStreak, SpacetimeDB.Identity>(tableName, "player_identity");
        }
    }
}
