// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Match
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "left_player")]
        public SpacetimeDB.Identity? LeftPlayer;
        [DataMember(Name = "right_player")]
        public SpacetimeDB.Identity? RightPlayer;
        [DataMember(Name = "state")]
        public int State;
        [DataMember(Name = "winner")]
        public SpacetimeDB.Identity? Winner;
        [DataMember(Name = "time_in_mil_second_player_left")]
        public float? TimeInMilSecondsPlayerLeft;
        [DataMember(Name = "time_in_mil_seconds_player_right")]
        public float? TimeInMilSecondsPlayerRight;
        [DataMember(Name = "left_player_ready")]
        public bool LeftPlayerReady;
        [DataMember(Name = "right_player_ready")]
        public bool RightPlayerReady;

        public Match(
            ulong Id,
            SpacetimeDB.Identity? LeftPlayer,
            SpacetimeDB.Identity? RightPlayer,
            int State,
            SpacetimeDB.Identity? Winner,
            float? timeInMilSecondsPlayerLeft,
            float? TimeInMilSecondsPlayerRight,
            bool LeftPlayerReady,
            bool RightPlayerReady
        )
        {
            this.Id = Id;
            this.LeftPlayer = LeftPlayer;
            this.RightPlayer = RightPlayer;
            this.State = State;
            this.Winner = Winner;
            this.TimeInMilSecondsPlayerLeft = timeInMilSecondsPlayerLeft;
            this.TimeInMilSecondsPlayerRight = TimeInMilSecondsPlayerRight;
            this.LeftPlayerReady = LeftPlayerReady;
            this.RightPlayerReady = RightPlayerReady;
        }

        public Match()
        {
        }
    }
}
