// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Player
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "snail_name")]
        public string SnailName;

        public Player(
            SpacetimeDB.Identity Identity,
            string SnailName
        )
        {
            this.Identity = Identity;
            this.SnailName = SnailName;
        }

        public Player()
        {
            this.SnailName = "";
        }
    }
}
