// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class WinStreak
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "player_identity")]
        public SpacetimeDB.Identity PlayerIdentity;
        [DataMember(Name = "current_win_streak")]
        public int CurrentWinStreak;
        [DataMember(Name = "max_win_streak")]
        public int MaxWinStreak;

        public WinStreak(
            ulong Id,
            SpacetimeDB.Identity PlayerIdentity,
            int CurrentWinStreak,
            int MaxWinStreak
        )
        {
            this.Id = Id;
            this.PlayerIdentity = PlayerIdentity;
            this.CurrentWinStreak = CurrentWinStreak;
            this.MaxWinStreak = MaxWinStreak;
        }

        public WinStreak()
        {
        }
    }
}
